export const PAGE_PERMISSIONS_SCHEMA = {
  projects: [
    { id: 'Overview', label: 'Overview' },
    { id: 'Team & Roles', label: 'Team & Roles' },
    { id: 'Client Profile', label: 'Client Profile' },
    { id: 'Site Details', label: 'Site Details' },
    { id: 'Vendors & Consultants', label: 'Vendors & Consultants' },
    { id: 'Settings', label: 'Settings' },
    { id: 'Financial Overview', label: 'Financial Overview' },
    { id: 'Booking', label: 'Booking' },
    { id: 'Meeting Notes', label: 'Meeting Notes' },
    { id: 'Site Visits', label: 'Site Visits' },
    { id: 'Baseline Assessment', label: 'Baseline Assessment' },
    { id: 'Delay Notifications', label: 'Delay Notifications' },
    { id: 'Handovers', label: 'Handovers' },
    { id: 'Design Brief', label: 'Design Brief' },
    { id: 'Design Assets', label: 'Design Assets' },
    { id: 'Design Reviews', label: 'Design Reviews' },
    { id: 'Material Palettes', label: 'Material Palettes' },
    { id: 'Quotations & BOQ', label: 'Quotations & BOQ' },
    { id: 'Commercial Approval', label: 'Commercial Approval' },
    { id: 'Change Orders', label: 'Change Orders' },
    { id: 'BOQ Variance', label: 'BOQ Variance' },
    { id: 'Budget', label: 'Budget' },
    { id: 'Purchase Requests', label: 'Purchase Requests' },
    { id: 'Purchase Orders', label: 'Purchase Orders' },
    { id: 'Material Deliveries', label: 'Material Deliveries' },
    { id: 'Vendors', label: 'Vendors' },
    { id: 'Vendor Payments', label: 'Vendor Payments' },
    { id: 'Substitutions', label: 'Substitutions' },
    { id: 'Factory Production', label: 'Factory Production' },
    { id: 'Coordination', label: 'Coordination' },
    { id: 'Phases', label: 'Phases' },
    { id: 'Gantt Chart', label: 'Gantt Chart' },
    { id: 'Work Activities', label: 'Work Activities' },
    { id: 'Room Progress', label: 'Room Progress' },
    { id: 'Tasks', label: 'Tasks' },
    { id: 'Daily Site Reports', label: 'Daily Site Reports' },
    { id: 'Weekly Reports', label: 'Weekly Reports' },
    { id: 'Documents', label: 'Documents' },
    { id: 'Drawing Register', label: 'Drawing Register' },
    { id: 'MEP Checklist', label: 'MEP Checklist' },
    { id: 'Payments', label: 'Payments' },
    { id: 'Execution QC', label: 'Execution QC' },
    { id: 'Snags', label: 'Snags' },
    { id: 'Punch List', label: 'Punch List' },
    { id: 'Handover', label: 'Handover' },
    { id: 'Warranties', label: 'Warranties' },
    { id: 'AMCs', label: 'AMCs' },
    { id: 'Handover Readiness', label: 'Handover Readiness' },
    { id: 'Service Tickets', label: 'Service Tickets' },
    { id: 'Customer Retention', label: 'Customer Retention' },
    { id: 'Project Closure', label: 'Project Closure' },
    { id: 'Retrospective', label: 'Retrospective' },
    { id: 'Activity Logs', label: 'Activity Logs' }
  ]
};
