/**
 * Base Webhook Provider Interface
 * All integrations (Standard, Slack, Teams) should extend this class.
 */
class BaseProvider {
  /**
   * Formats the final request configuration for Axios.
   * @param {Object} webhook The database webhook record
   * @param {String} eventType The CRM event string (e.g. 'customer.created')
   * @param {Object} payload The raw payload generated by the CRM
   * @returns {Object} { url, headers, bodyString }
   */
  formatRequest(webhook, eventType, payload) {
    throw new Error('formatRequest() must be implemented by Provider');
  }

  /**
   * Helper to interpolate string templates
   */
  interpolatePayload(templateObj, payload) {
    let templateStr = JSON.stringify(templateObj);
    templateStr = templateStr.replace(/\{\{([^}]+)\}\}/g, (match, path) => {
      const keys = path.trim().split('.');
      let val = payload;
      for (const k of keys) {
        if (val === undefined || val === null) break;
        val = val[k];
      }
      if (typeof val === 'string') {
        return val.replace(/"/g, '\\"');
      }
      if (typeof val === 'number' || typeof val === 'boolean') {
        return val;
      }
      return val === undefined || val === null ? '' : JSON.stringify(val).replace(/"/g, '\\"');
    });
    
    try {
      return JSON.parse(templateStr);
    } catch (e) {
      return payload;
    }
  }
}

module.exports = BaseProvider;
