ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS device VARCHAR(255);
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS reason TEXT;

